version: 2
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
run:
  - pip install -r web/requirements_offline.txt
  - cd web && python install_models.py
deploy:
  restart-policy: on-failure
web:
  - cd web && python app_offline.py
